# Butterfly Theme Configuration Override
# 覆盖Butterfly主题的默认配置

menu:
  首页: / || fas fa-home
  关于我: /about/ || fas fa-heart

# 目录设置
toc:
  post: true
  page: false
  number: false  # 设置为false以取消目录的自动编号
  expand: false
  style_simple: false
  scroll_percent: true

social:
  fab fa-github: https://github.com/1935zz || Github || "#hdhfbb"

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description: # 你可以在这里添加个人简介，或者留空
    button:
      enable: false  # 设置为 false 来隐藏 Follow Me 按钮
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    # If set 0 will show all
    limit: 5
    # Sort: date / updated
    sort: date
    sort_order:
  card_newest_comments:
    enable: false
    sort_order:
    limit: 6
    # Unit: mins, save data to localStorage
    storage: 10
    avatar: true
  card_categories:
    enable: true
    # If set 0 will show all
    limit: 8
    # Choose: none / true / false
    expand: none
    sort_order:
  card_tags:
    enable: true
    # If set 0 will show all
    limit: 40
    color: false
    # Order of tags, random/name/length
    orderby: random
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: 1
    sort_order:
  card_archives:
    enable: true
    # Type: monthly / yearly
    type: monthly
    # Eg: YYYY年MM月
    format: MMMM YYYY
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
    # If set 0 will show all
    limit: 8
    sort_order:
  card_post_series:
    enable: true
    # The title shows the series name
    series_title: false
    # Order by title or date
    orderBy: 'date'
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:
    # Time difference between publish date and now
    # Formal: Month/Day/Year Time or Year/Month/Day Time
    # Leave it empty if you don't enable this feature
    runtime_date:


作者: Jerry
連結: https://butterfly.js.org/posts/4aa8abbe/
來源: Butterfly
版權屬於作者所有。商業用途請聯絡作者獲得授權，非商業用途請註明出處。

# 头像设置
avatar:
  img: /img/avatar.png  # 头像图片路径，可以是本地路径或网络链接
  effect: false  # 头像特效，true为开启鼠标悬停转动效果

# --------------------------------------
# 導航設置
# --------------------------------------

nav:
  # 導航欄 Logo 圖片
  logo:
  # 是否顯示標題
  display_title: true
  # 是否在滾動時顯示文章標題
  display_post_title: true
  # 是否固定導航欄
  fixed: false

default_top_img: /img/default-img.jpg  # 默认顶部图片路径