# Butterfly Theme Configuration Override
# 覆盖Butterfly主题的默认配置

menu:
  首页: / || fas fa-home
  关于我: /about/ || fas fa-heart

# 目录设置
toc:
  post: true
  page: false
  number: false  # 设置为false以取消目录的自动编号
  expand: false
  style_simple: false
  scroll_percent: true

social:
  fab fa-github: https://github.com/1935zz || Github || "#hdhfbb"

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description: # 你可以在这里添加个人简介，或者留空
    button:
      enable: false  # 设置为 false 来隐藏 Follow Me 按钮